
adj = input()
noun = input()
verb = input()
adv = input()

print("Today I went to the zoo. I saw a(n)")
print(f"{adj} (adjective)")
print(f"{noun} (Noun) jumping up and down in its tree.")
print(f"He {verb} (verb,past tense ) {adv} (adverb)")
print(f"through the large tunnel that led to its {adj} (adjective")
print(f"{noun} (noun) I got some peanuts and passed")
print(f"them through the cage to a gigantic gray {noun} (noun)")
print("towering above my head. Feeding that animal made")
print(f"me hungry. I went to get a {adj} (adjective) scoop")
print("of ice cream. It filled my stomach. Afterwards I had to")
print(f"{verb} (verb) {adv} (adverb) to catch our bus.")
print(f"When I got home I {verb} (verb, past tense) my")
print(F"mom for a {adj} (adjective) day at the zoo.")