# Generated by Django 3.0.6 on 2020-07-08 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.IntegerField()),
                ('birthday', models.DateTimeField()),
                ('over_21', models.BooleanField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='main.City')),
            ],
        ),
    ]
