# Generated by Django 3.0.6 on 2020-07-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200708_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(default='USA', max_length=200),
            preserve_default=False,
        ),
    ]
