# Generated by Django 3.0.6 on 2020-06-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(verbose_name='date published')),
                ('completed_date', models.DateTimeField(verbose_name='date completed')),
                ('task', models.CharField(max_length=200)),
            ],
        ),
    ]
