# Generated by Django 3.0.6 on 2020-06-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_auto_20200603_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image_back',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image_front',
            field=models.URLField(),
        ),
    ]
