# Generated by Django 3.0.6 on 2020-06-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_auto_20200604_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemontype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='pokemontype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
