amount = float(input('Please enter in a dollar amount: '))
quarters = (amount // .25)
quarters_remainder = (amount % .25)
dimes = (quarters_remainder // .10)
dimes_remainder = (quarters_remainder % .10)
nickels = (dimes_remainder // .5)
nickels_remainder = (dimes_remainder % .5)
pennies = (nickels_remainder // .01)
print(f'Quarters {quarters}, Dimes {dimes}, Nickels {nickels}, Pennies {pennies}')
