# Generated by Django 3.0.6 on 2020-06-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
