# Generated by Django 3.0.6 on 2020-06-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_pokemon_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemontype',
            options={'ordering': ['name']},
        ),
    ]
