# Generated by Django 3.0.6 on 2020-05-28 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('population', models.IntegerField()),
                ('gdp', models.FloatField()),
                ('hot_or_not', models.BooleanField(default=True)),
                ('founding_day', models.DateTimeField()),
                ('ending_day', models.DateTimeField(blank=True, null=True)),
                ('capital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demo.CapitalCity')),
            ],
        ),
    ]
