# Generated by Django 3.0.6 on 2020-05-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_city_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
