# Generated by Django 3.0.6 on 2020-05-27 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='todo.Priority'),
            preserve_default=False,
        ),
    ]
