# Generated by Django 3.0.6 on 2020-06-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemontype',
            old_name='pokemon_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(related_name='pokemon', to='pokedex.PokemonType'),
        ),
    ]
