# Generated by Django 3.0.6 on 2020-06-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_auto_20200602_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image_back',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image_front',
            field=models.ImageField(upload_to=''),
        ),
    ]
