# Generated by Django 3.0.6 on 2020-05-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField()),
                ('completed', models.BooleanField()),
            ],
        ),
    ]
