# Generated by Django 3.0.6 on 2020-05-28 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
               ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('birthday', models.DateField()),
                ('phone_number', models.CharField(max_length=14)),
                ('is_cell', models.BooleanField(default=True)),
                ('comments', models.TextField(max_length=200))
            ],
        ),
    ]
