# Generated by Django 3.0.6 on 2020-06-04 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactsapp',
            new_name='ContactType',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='body',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='author',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='title',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='type',
        ),
        migrations.AddField(
            model_name='contacts',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='first_name',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='is_cell',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='last_name',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone_number',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
