# Generated by Django 3.0.6 on 2020-05-21 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20200521_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='blogapp.BlogPostType'),
            preserve_default=False,
        ),
    ]
