# Generated by Django 3.0.6 on 2020-05-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200528_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='age',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='contact',
            name='comments',
            field=models.TextField(default='default comment', max_length=99),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='is_cell',
            field=models.BooleanField(default=True, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default='111-111-1111', max_length=20),
            preserve_default=False,
        ),
    ]
