# Generated by Django 3.0.6 on 2020-07-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_auto_20200603_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemontype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='pokemon',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
