# Generated by Django 3.0.6 on 2020-07-29 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_auto_20200728_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='url',
        ),
    ]
