# Generated by Django 3.0.6 on 2020-06-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
