# Generated by Django 3.0.6 on 2020-05-28 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='comment',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='birthday',
        ),
        migrations.AddField(
            model_name='contacts',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
