# Generated by Django 3.0.6 on 2020-05-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200528_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='birth_date',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
    ]
