# Generated by Django 3.0.6 on 2020-06-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20200529_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
