# Generated by Django 3.0.6 on 2020-07-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='favqs_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
