# Generated by Django 3.0.6 on 2020-07-30 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='age',
        ),
    ]
