# Generated by Django 3.0.6 on 2020-05-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_auto_20200526_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
