# Generated by Django 3.0.6 on 2020-06-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_auto_20200604_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image_back',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image_front',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(related_name='pokemon_set', to='pokedex.PokemonType'),
        ),
        migrations.AlterField(
            model_name='pokemontype',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
