# Generated by Django 3.0.6 on 2020-06-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200530_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='age',
            field=models.IntegerField(),
        ),
    ]
