# Generated by Django 3.0.6 on 2020-05-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_cell',
            field=models.BooleanField(default=True),
        ),
    ]
