# Generated by Django 3.0.6 on 2020-05-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_is_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_cell',
            field=models.BooleanField(),
        ),
    ]
