# Generated by Django 3.0.6 on 2020-06-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_auto_20200602_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(to='pokedex.PokemonType'),
        ),
    ]
