# Generated by Django 3.0.6 on 2020-06-26 00:02

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birthday',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=10),
        ),
    ]
