# Generated by Django 3.0.6 on 2020-06-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_auto_20200602_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ['name']},
        ),
    ]
