# Generated by Django 3.0.6 on 2020-06-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_auto_20200604_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemontype',
            options={'ordering': ['name']},
        ),
    ]
