# Generated by Django 3.0.6 on 2020-05-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20200526_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='completed_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todos',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
