# Generated by Django 3.0.6 on 2020-06-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('created_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
