# Generated by Django 3.0.6 on 2020-06-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pokedex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('height', models.IntegerField(max_length=20)),
                ('weight', models.IntegerField(max_length=20)),
                ('image_front', models.URLField()),
                ('image_back', models.URLField()),
                ('types', models.CharField(max_length=20)),
                ('url', models.URLField()),
            ],
        ),
    ]
