# Generated by Django 3.0.6 on 2020-06-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200601_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='test@gmail.com', max_length=50),
            preserve_default=False,
        ),
    ]
