# Generated by Django 3.0.6 on 2020-07-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20200630_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
