# Generated by Django 3.0.6 on 2020-07-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
